esphome:
    name: hpsu-can
    friendly_name: HPSU.CAN
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN.git
      ref: main   # Sostituire “main” con “dev” se si vuole usare il ramo di sviluppo
    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

button:
  - platform: restart
    name: "Rotex ESP Restart"
#switch:
#  - platform: gpio
#    name: Smart Grid
#    pin:
#      number: GPIO06
#      inverted: true

#  - platform: gpio
#    name: EVU
#    pin:
#      number: GPIO05
#      inverted: true

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO5
    rx_pin: GPIO6
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  language: it
  canbus_id: can_bus
  update_interval: 30

  # Alcuni sensori Tv, TvBH o Tr forniscono valori con deviazioni.
  # Queste deviazioni possono essere corrette utilizzando un offset per migliorare la precisione nel rilevamento di valvole a 3 vie difettose.
  # Ad esempio, se il sensore Tv mostra una temperatura superiore di 1,5°C, l'offset Tv dovrebbe essere impostato a -1,5.
  # Se invece fornisce valori inferiori di 1,2°C, l'offset dovrebbe essere impostato a 1,2.
  # Lo stesso vale per TvBH e Tr.
  #tv_offset: -1.0
  #tvbh_offset: -1.0
  #tr_offset: -1.0

  #max_spread_tvbh_tv: 0.5  # Legt Tv-TVBH-Schwellwert fest, bei dem die DHW-Ventil-Fehler-Erkennung auslösen soll
  #max_spread_tvbh_tr: 0.5  # Legt TVBH-Tr-Schwellwert fest, bei dem die BPV-Ventil-Fehler-Erkennung auslösen soll

  log_filter:
    name: Log Filter
  custom_request:
    name: Custom Request
  dump:
    name: Dump Senors
  project_git_hash:
    name: Project Git Hash
  entities:

# Info

    error_code:
      name: Codice di Errore

    mode_of_operating:
      name: Stato operativo
    ext:
      name: Esterno
# RT
    circulation_pump:
      name: Pompa di Circolazione
# EHS
    bypass_valve:
      name: Valvola di Bypass
    tv:
      name: Temperatura di mandata (TV)
      update_interval: 5
    tvbh:
      name: Temperatura Mandata Riscaldamento (TVBH)
      update_interval: 5
    tr:
      name: Temperatura Ritorno Riscaldamento
      update_interval: 5
    tdhw1:
      name: Temperatura Acqua Calda
    tdhw2:
      name: Temperatura Acqua Calda 2
    temperature_outside:
      name: Temperatura Esterna
# V
# TVBH2
# TR2
# Tdhw2
    tliq:
      name: Temperatura linea liquido
    ta2:
      name: TA2
# quiet

# Übersicht
    water_pressure:
      name: Pressione dell'Acqua
    t_hs:
      name: T-WE
# T-WE Soll
    t_ext:
      name: T-Esterno
# T-WW
# T-WW Soll
# T-Rücklauf
    flow_rate:
      name: Portata
      update_interval: 10
# T-HK
# T-HK Soll
    status_kesselpumpe:
      name: Stato Pompa Circolazione
    status_kompressor:
      name: Stato Compressore
    runtime_compressor:
      name: Tempo di Funzionamento Compressore
    runtime_pump:
      name: Tempo di Funzionamento Pompa
    dhw_mixer_position:
      name: Posizione Miscelatore ACS
    qboh:
      name: EHS per ACS
    ehs_for_ch:
      name: EHS per CH
    energy_cooling:
      name: Energia Raffreddamento
    qch:
      name: Energia Riscaldamento
    total_energy_produced:
      name: Energia Totale Prodotta
    qdhw:
      name: Energia per ACS
    total_electrical_energy:
      name: Energia Elettrica Totale
#WE Typ
#SwNr B1/U1
#SwNr Regler
#SwNr RTXRT

# ESP custom sensors
    energy_saving_mode:
      name: Modalità Risparmio Energetico

# Betriebsart
    operating_mode:
      name: Modalità di Funzionamento
      update_interval: 5

# Raum Soll Tag
    target_room1_temperature:
      name: Temperatura Obiettivo Stanza 1
      type: select
# T-RaumSoll 2
# T-RaumSoll 3

# Raum Soll Nacht
  # T-Absenkung
  # T-Abwesend

# WW Solltemp
    target_hot_water_temperature:
      name: Temperatura Obiettivo ACS
      type: select

# T-WWSoll 2
# T-WWSoll 3

# WW Install
    dhw_run:
      name: Esecuzione ACS
    1_dhw:
      name: 1 x Acqua Calda
    hp_hyst_tdhw:
      name: HP Hyst TDHW
    delay_time_for_backup_heating:
      name: Tempo di Attesa per Riscaldamento di Backup

# Konfiguration

# Konfiguration -> Installation
# Sprache
# Datum
    #system_date_day:
    #  name: Giorno della data di sistema
    #  internal: true
    #system_date_month:
    #  name: Mese della data di sistema
    #  internal: true
    #system_date_year:
    #  name: Anno della data di sistema
    #  internal: true
    #system_date:
    #  name: Data di sistema
# Uhrzeit
    #system_time_hour:
    #  name: Ora del sistema
    #  internal: true
    #system_time_minute:
    #  name: Minuto del sistema
    #  internal: true
    #system_time_second:
    #  name: Secondo del sistema
    #  internal: true
    #  update_interval: 1
    #system_time:         # Questa entità fa crescere rapidamente il database di HA! Per favore, aggiungila in HA -> recorder -> exclude -> entities!
    #  name: Ora di sistema

#...
    outdoor_unit:
      name: Unità Esterna
    indoor_unit:
      name: Unità Interna
    function_ehs:
      name: Funzione EHS
    ch_support:
      name: Supporto CH
    bivalence_function:
      name: Funzione di Bivalenza
    smart_grid:
      name: Smart Grid
    sg_mode:
      name: Modalità SG
# HT/NT Funktion
# HT/NT Anschluss
# Raumthermostat
# Interlinkfunktion
# Konfig MFR 1
# Entlüftungsfunktion
# PWM Konfig
    circulation_pump_min:
      name: Pompa di Circolazione Minima
    circulation_pump_max:
      name: Pompa di Circolazione Massima
# ...
# Sensor Konfig
    external_temp_sensor:
      name: Sensore Temperatura Esterna
    # SKonfig T-WW
    # SKonfig Druck
# AF Anspassung
# Terminal Adresse
# Konfig System

# Konfiguration -> Anlagenkonfiguration

    power_dhw:
      name: Potenza ACS
      #type: select
    power_ehs_1:
      name: Potenza EHS Livello 1
    power_ehs_2:
      name: Potenza EHS Livello 2
    power_biv:
      name: Potenza BIV
    tdiff_dhw_ch:
      name: TDiff ACS CH
    max_heating_temperature:
      name: Temperatura Massima Riscaldamento
    bivalence_temperature:
      name: Temperatura di Bivalenza
    quiet:
      name: Modalità Silenziosa
#Sonderfunkt Schaltk
#Wartezeit Sonderfunkt
    t_dhw_1_min:
      name: Soglia di Commutazione TDHW
    delta_temp_ch:
      name: Differenza Temperatura CH
    delta_temp_dhw:
      name: Differenza Temperatura ACS
#VerzZeitPumpe                # service
    flow_rate_min:
      name: Portata Minima
    flow_rate_setpoint:
      name: Setpoint Portata
    flow_rate_calc:
      name: Portata Calcolata
    flow_rate_hyst:
      name: Isteresi Portata
    supply_temperature_adjustment_heating:
      name: Regolazione Temperatura Mandata Riscaldamento
    supply_temperature_adjustment_cooling:
      name: Regolazione Temperatura Mandata Raffreddamento
    min_pressure:
      name: Pressione Minima
    max_pressure:
      name: Pressione Massima
    set_pressure:
      name: Pressione Desiderata
    max_pressure_drop:
      name: Perdita di Pressione Massima
#Relaistest

# Konfiguration -> HZK Konfig
    hk_function:
      name: Funzione HK
    temperature_antifreeze:
      name: Temperatura Antigelo
    building_insulation:
      name: Isolamento Dell’edificio
#Estrich
#Estrichprogramm

# Konfiguration -> HZK Konfig -> Heizen

    heating_limit_day:
      name: Limite Riscaldamento Giorno
    heating_limit_night:
      name: Limite Riscaldamento Notte
    heating_curve:
      name: Curva di Riscaldamento
#Raumeinfluss
#RF Anpassung
    flow_temperature_day:
      name: Temperatura Mandata Giorno
    flow_temperature_night:
      name: Temperatura Mandata Notte
    max_target_flow_temp:
      name: Temperatura Massima Mandata Obiettivo
    min_target_flow_temp:
      name: Temperatura Minima Mandata Obiettivo
    heating_curve_adaptation:
      name: Adattamento delle curve di riscaldamento

# Konfiguration -> HZK Konfig -> Kühlen

#StartKühlen A-Temp
#MaxKühlen A-Temp
#VL-SollStartKühlen
#VL-SollMaxKühlen
#MinVL-SollKühlen
#T-VLKühlen
#T_H/K Umschaltung
#KühlsollwertKorr

#Konfiguration -> WW Konfig

    circulation_with_dhw_program:
      name: Circolazione con Programma ACS
    circulation_interval_on:
      name: Intervallo Circolazione On
    circulation_interval_off:
      name: Intervallo Circolazione Off
    antileg_day:
      name: Giorno Anti-Legionella
#AntilegZeit
    antileg_temp:
      name: Temperatura Anti-Legionella
    max_dhw_loading:
      name: Tempo Massimo di Caricamento ACS
    dhw_off_time:
      name: Tempo di Spegnimento ACS

# Others

    electric_heater:
      name: Resistenze Elettriche - Per Pompe dopo Ottobre 2018
    thermal_power:
      name: Potenza Termica
    optimized_defrosting:
      name: Sbrinamento Ottimizzato
    temperature_spread:
      name: Delta Termico"
    tv_tvbh_delta:
      name: Tv-TVBH Delta
    tvbh_tr_delta:
      name: TVBH-Tr Delta
    vorlauf_soll_tv_delta:
      name: Mandata Setpoint - T. Mandata

# Rocon U1

    #t_room:
    #  name: Temperatura Attuale del Locale

# To be categorized

    target_supply_temperature:
      name: Temperatura Mandata Obiettivo
    supply_setpoint_regulated:
      name: Setpoint Mandata Regolato
